export const doctorsData = [
  {
    id: 1,
    name: 'Dr. Ram Sharma',
    specialty: 'Cardiology',
    experience: 12,
    rating: 4.9,
    reviews: 127,
    location: 'Kathmandu',
    availability: 'Available Today',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop&crop=face',
    hospital: 'Tribhuvan University Teaching Hospital',
    consultationFee: 1500,
    education: 'MBBS, MD (Cardiology)',
    languages: ['English', 'Nepali', 'Hindi'],
    bio: 'Expert cardiologist with 12 years of experience in interventional cardiology. Specialized in treating complex cardiac conditions and performing advanced cardiac procedures.'
  },
  {
    id: 2,
    name: 'Dr. Sita Gurung',
    specialty: 'Dermatology',
    experience: 8,
    rating: 4.8,
    reviews: 89,
    location: 'Lalitpur',
    availability: 'This Week',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face',
    hospital: 'Patan Hospital',
    consultationFee: 1200,
    education: 'MBBS, MD (Dermatology)',
    languages: ['English', 'Nepali'],
    bio: 'Specialized in aesthetic and clinical dermatology. Expert in treating skin conditions and providing advanced dermatological care.'
  },
  {
    id: 3,
    name: 'Dr. Hari Adhikari',
    specialty: 'Neurology',
    experience: 15,
    rating: 4.7,
    reviews: 203,
    location: 'Kathmandu',
    availability: 'Available Today',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&h=150&fit=crop&crop=face',
    hospital: 'B and B Hospital',
    consultationFee: 2000,
    education: 'MBBS, MD (Neurology), Fellowship in Stroke',
    languages: ['English', 'Nepali'],
    bio: 'Stroke specialist with advanced training in neuro-interventional procedures. Committed to providing comprehensive neurological care.'
  },
  {
    id: 4,
    name: 'Dr. Laxmi Poudel',
    specialty: 'Pediatrics',
    experience: 10,
    rating: 4.9,
    reviews: 156,
    location: 'Bhaktapur',
    availability: 'Next Week',
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=150&h=150&fit=crop&crop=face',
    hospital: 'Kantipur Hospital',
    consultationFee: 1000,
    education: 'MBBS, MD (Pediatrics)',
    languages: ['English', 'Nepali'],
    bio: 'Dedicated to providing compassionate care for children of all ages. Specialized in pediatric infectious diseases and child development.'
  },
  {
    id: 5,
    name: 'Dr. Bijay Shrestha',
    specialty: 'Orthopedics',
    experience: 14,
    rating: 4.8,
    reviews: 178,
    location: 'Kathmandu',
    availability: 'Available Today',
    image: 'https://images.unsplash.com/photo-1618498082410-b4aa22193b38?w=150&h=150&fit=crop&crop=face',
    hospital: 'Nepal Orthopedic Hospital',
    consultationFee: 1800,
    education: 'MBBS, MS (Orthopedics)',
    languages: ['English', 'Nepali', 'Newari'],
    bio: 'Specializing in joint replacement and sports medicine. Expert in treating orthopedic conditions and performing advanced surgical procedures.'
  },
  {
    id: 6,
    name: 'Dr. Sunita Karki',
    specialty: 'Gynecology',
    experience: 9,
    rating: 4.9,
    reviews: 234,
    location: 'Lalitpur',
    availability: 'This Week',
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=150&h=150&fit=crop&crop=face',
    hospital: 'Maternity Hospital',
    consultationFee: 1400,
    education: 'MBBS, MS (Obstetrics & Gynecology)',
    languages: ['English', 'Nepali'],
    bio: 'Committed to women\'s health and well-being. Specialized in high-risk pregnancies and minimally invasive gynecological surgery.'
  },
  {
    id: 7,
    name: 'Dr. Kiran Nepal',
    specialty: 'Ophthalmology',
    experience: 11,
    rating: 4.7,
    reviews: 98,
    location: 'Kathmandu',
    availability: 'Next Week',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&h=150&fit=crop&crop=face',
    hospital: 'Nepal Eye Hospital',
    consultationFee: 1300,
    education: 'MBBS, MS (Ophthalmology)',
    languages: ['English', 'Nepali'],
    bio: 'Expert in cataract surgery and refractive surgery. Dedicated to providing comprehensive eye care services.'
  },
  {
    id: 8,
    name: 'Dr. Raju Thapa',
    specialty: 'ENT',
    experience: 7,
    rating: 4.6,
    reviews: 67,
    location: 'Bhaktapur',
    availability: 'Available Today',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&h=150&fit=crop&crop=face',
    hospital: 'ENT Care Center',
    consultationFee: 1100,
    education: 'MBBS, MS (ENT)',
    languages: ['English', 'Nepali'],
    bio: 'Specializing in otology and sinus surgery. Committed to providing advanced ENT care with a patient-centered approach.'
  },
  {
    id: 9,
    name: 'Dr. Gita Sharma',
    specialty: 'Psychiatry',
    experience: 10,
    rating: 4.8,
    reviews: 145,
    location: 'Kathmandu',
    availability: 'This Week',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&h=150&fit=crop&crop=face',
    hospital: 'Mental Health Center',
    consultationFee: 1600,
    education: 'MBBS, MD (Psychiatry)',
    languages: ['English', 'Nepali', 'Hindi'],
    bio: 'Dedicated to providing comprehensive mental health services. Specialized in treating depression, anxiety, and other psychiatric disorders.'
  },
  {
    id: 10,
    name: 'Dr. Madan Rajbhandari',
    specialty: 'Urology',
    experience: 16,
    rating: 4.9,
    reviews: 189,
    location: 'Lalitpur',
    availability: 'Available Today',
    image: 'https://images.unsplash.com/photo-1618498082410-b4aa22193b38?w=150&h=150&fit=crop&crop=face',
    hospital: 'Urology Center Nepal',
    consultationFee: 1900,
    education: 'MBBS, MS (Urology)',
    languages: ['English', 'Nepali'],
    bio: 'Expert urologist with advanced training in minimally invasive urological surgery and robotic procedures.'
  }
];